### ISSUE TITLE
Migration to PyQt5 5.15: issues detected by MyPy

### ISSUE THREAD

**Issue by jfisteus** [jfisteus/eyegrade#158]
After migrating PyQt5 from 5.14 to 5.15 MyPy detects the following issues:

```
eyegrade/qtgui/widgets.py:41: error: Module "PyQt5.QtCore" has no attribute "pyqtProperty"
eyegrade/qtgui/students.py:643: error: "Type[Qt]" has no attribute "AlignRight"
eyegrade/qtgui/students.py:644: error: "Type[Qt]" has no attribute "AlignRight"
eyegrade/qtgui/students.py:645: error: "Type[Qt]" has no attribute "AlignLeft"
eyegrade/qtgui/students.py:646: error: "Type[Qt]" has no attribute "AlignLeft"
eyegrade/qtgui/students.py:647: error: "Type[Qt]" has no attribute "AlignLeft"
eyegrade/qtgui/students.py:648: error: "Type[Qt]" has no attribute "AlignLeft"
eyegrade/qtgui/students.py:649: error: "Type[Qt]" has no attribute "AlignLeft"
eyegrade/qtgui/gui.py:106: error: "Type[Qt]" has no attribute "Key_Space"
eyegrade/qtgui/gui.py:108: error: "Type[Qt]" has no attribute "Key_C"
eyegrade/qtgui/gui.py:113: error: "Type[Qt]" has no attribute "Key_M"
eyegrade/qtgui/gui.py:115: error: "Type[Qt]" has no attribute "Key_I"
eyegrade/qtgui/gui.py:120: error: "Type[Qt]" has no attribute "Key_Delete"
eyegrade/qtgui/gui.py:120: error: "Type[Qt]" has no attribute "Key_Backspace"
eyegrade/qtgui/gui.py:127: error: "Type[Qt]" has no attribute "Key_Escape"
Found 15 errors in 3 files (checked 50 source files)
```

**Comment by jfisteus** [comment]
Closed by commit fcbaf2e30cea
